<?php
/**
 * Templates for output filters
 *
 * @since 0.40.0
 * @package WordPress
 * @subpackage A.N.R.GHG Publishing Toolkit
 *
 * CAUTION: Please do not edit this file in this plugin folder,
 * since it is not included when WordPress loads this plugin,
 * and because it will be overwritten during plugin updates.
 *
 * HOW TO: Copy-paste any of these templates into a mini plugin
 * and edit the return value.
 * A template for a mini plugin is included in this folder.
 * @see ./template-mini-plugin.php
 *
 * HOOK NAMES: Names of hooks for output filters all start with
 * `anrghg_` and end with `_hook`, to make them stand out among
 * another set of hooks, that are named after settings keys, as
 * documented in the configuration filter template file.
 * @see ./template-filter-config.php
 *
 * This file is not a part of the plugin’s code.
 */

defined( 'ABSPATH' ) || exit( nl2br( "\r\n\r\n&nbsp; &nbsp; &nbsp; Sorry, this PHP file cannot be displayed in the browser." ) );

/**
 * Specific content filter hook: `anrghg_the_content`.
 *
 * @since 0.40.0
 * All filters applied to `the_content` and only those, are also
 * applied to this hook, whose purpose covers special use cases,
 * that might relate to custom post types.
 */
$content = apply_filters( 'anrghg_the_content', $content );

/**
 * Security: `anrghg_deactivated_login_message_hook`.
 *
 * @since 0.47.0
 * Edit the message displayed on the high-profile deactivation screen.
 *
 * Callback function:
 * @param  $message  Localized hard-coded message.
 * @return $message  Customized message.
 */
add_filter(
	'anrghg_deactivated_login_message_hook',
	function( $message ) {
		$message = 'Deactivated action: login.';
		return $message;
	}
);

/**
 * Security: `anrghg_deactivated_login_screen_hook`.
 *
 * Edit the markup displayed on high-profile deactivation screen.
 *
 * @since 0.40.0
 * @since 0.47.0 Parameters instead of echo.
 *
 * Callback function:
 * @param  string $output  Hard-coded output.
 * @param  string $message Passed-on parameter.
 * @return string $output  Customized output.
 */
add_filter(
	'anrghg_deactivated_login_screen_hook',
	function( $output, $message ) {
		$output = "
			</div>
			<div style=\"text-align: center; font-size: 18px;
			background: #E76262; padding: 30px;\">
				<p>$message</p>
			</div>
		";
		return $output;
	},
	10,
	2
);

/**
 * Example editing the band’s background color only.
 */
add_filter(
	'anrghg_deactivated_login_screen_hook',
	function( $output ) {
		$output = str_replace( '#E76262', '#7B65FB', $output );
		return $output;
	}
);

/**
 * Thank You message: `anrghg_thank_you_post_hook`
 *
 * @since 0.69.0
 * Edit the markup around the message content for posts.
 *
 * Callback function:
 * @param  string $output  Hard-coded output.
 * @param  string $message Passed-on parameter.
 * @return string $output  Customized output.
 */
add_filter(
	'anrghg_thank_you_post_hook',
	function( $output, $message ) {
		$output = "<div class=\"anrghg-post-thanks\"
		tabindex=\"0\"><div>$message</div></div><!--.anrghg-post-thanks-->";
		return $output;
	},
	10,
	2
);

/**
 * Thank You message: `anrghg_thank_you_page_hook`
 *
 * @since 0.69.0
 * Edit the markup around the message content for pages.
 *
 * Callback function:
 * @param  string $output  Hard-coded output.
 * @param  string $message Passed-on parameter.
 * @return string $output  Customized output.
 */
add_filter(
	'anrghg_thank_you_page_hook',
	function( $output, $message ) {
		$output = "<div class=\"anrghg-page-thanks\"
			tabindex=\"0\"><div>$message</div></div><!--.anrghg-page-thanks-->";
		return $output;
	},
	10,
	2
);

/**
 * Notes and sources: `anrghg_anchor_tooltip_hook`
 *
 * @since 0.73.0
 *
 * Callback function:
 * @param  string $output               Hard-coded output.
 * @param  string $tooltip_text         Passed-on parameter.
 * @param  string $writing_direction    Assessed by the logic.
 * @param  bool   $display_full_width   Depends on text length.
 * @param  string $display_checkbox_id  Passed-on parameter.
 * @param  bool   $display_on_tap       Configurable boolean.
 * @return string $output               Customized output.
 */
add_filter(
	'anrghg_anchor_tooltip_hook',
	function(
		$output,
		$tooltip_text,
		$writing_direction,
		$display_full_width,
		$display_checkbox_id,
		$display_on_tap
	) {
		$output = '';
		if ( $display_on_tap ) {
			$output .= "<input type=\"checkbox\" id=\"$display_checkbox_id\"
				class=\"anrghg-tooltip-display-toggle\" />";
		}
		$output .= '<span class="anrghg-complement-tooltip';
		if ( $display_full_width ) {
			$output .= ' anrghg-fullwidth';
		} else {
			$output .= ' anrghg-classic';
		}
		$output .= "\" dir=\"$l_s_dir\">";
		if ( $display_on_tap ) {
			$output .= "<label for=\"$l_s_display_checkbox_id\"><span
				class=\"anrghg-tooltip-close-button\"></span></label>";
		}
		$output .= "$l_s_tooltip_text</span>";
		return $output;
	},
	10,
	6
);
